In [ ]:
import pandas as pd
# import openai
from time import time , sleep
import json
import openai

df=pd.read_csv(r'test_data.csv')

In [ ]:
import re
def remove_urls(text):
    # Define regex pattern to match URLs starting with http:// or https://
    url_pattern = r'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'

    # Replace URLs with an empty string
    text_without_urls = re.sub(url_pattern, '', text)

    return text_without_urls

df['Link_removed']=df['tweet'].apply(remove_urls)

In [ ]:
df=df.iloc[445:]

In [ ]:
len(df)

415

In [ ]:
# install open ai library
!pip install openai

Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.84.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.10.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from openai) (2.11.5)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.14.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (2025.4.26)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.1)

In [ ]:
openai.api_key = 'Your_Key'

In [ ]:
prompt_template = """
You are an expert text classifier. Your task is to classify the following text into one of three categories: "Anti-Vaccine", "Neutral", or "Pro-Vaccine". Here are the definitions of each category:
Anti-Vaccine: means someone who has a negative opinion about the vaccine and its sidelines and opposes its use It does not recommend,
Neutral: means the sentence is news or quotation, the user's position is neutral.
Pro-Vaccine:pro-vaccine classes means someone who encourages and supports the vaccine and vaccination and its sidelines
```
{comment}
```
Your response should be one of the following labels: Anti-Vaccine, Neutral, Pro-Vaccine.
"""

In [ ]:
text = df['Link_removed'].to_list()

In [ ]:
awnser = []

In [ ]:
stopIter = len(text)
counter = 0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
while True:
  try:
    if counter >= stopIter:
      break
    res = get_completion(prompt_template.format(comment=text[counter]))
    # append response to text file
    f = open("/content/drive/MyDrive/stance.txt", "a")
    f.write('\n')
    f.write(str(counter)+' : ' + res)
    awnser.append(res)
    f.write(',')
    f.close()
    counter +=1
  except Exception  as e:
    print(e)
    # for limit rate wait for 20 seconds
    sleep(20)

In [ ]:
exist = pd.read_csv(r'/content/stance.txt',header=None)
index = exist[0].str.split(':',expand=True)
index[0] = index[0].astype(int)
index.sort_values(by=0,inplace=True)

In [ ]:
exist

                      0   1
0           0 : Neutral NaN
1           1 : Neutral NaN
2           2 : Neutral NaN
3       3 : Pro-Vaccine NaN
4      4 : Anti-Vaccine NaN
..                  ...  ..
855   855 : Pro-Vaccine NaN
856       856 : Neutral NaN
857  857 : Anti-Vaccine NaN
858   858 : Pro-Vaccine NaN
859  859 : Anti-Vaccine NaN

[860 rows x 2 columns]

In [ ]:
label=[]
for i in range(len(exist)):
  label.append(exist.iloc[i][0].split(':')[1])

In [ ]:
label=pd.DataFrame(label,columns=['label'])

In [ ]:
label

             label
0          Neutral
1          Neutral
2          Neutral
3      Pro-Vaccine
4     Anti-Vaccine
..             ...
855    Pro-Vaccine
856        Neutral
857   Anti-Vaccine
858    Pro-Vaccine
859   Anti-Vaccine

[860 rows x 1 columns]

In [ ]:
label['label'] = label['label'].astype(str)

label['label'] = label['label'].str.strip()

unique_labels = label['label'].unique()
print("Unique labels:", unique_labels)

label_rows = label[label['label'] == 'Label']

print(label_rows)

Unique labels: ['Neutral' 'Pro-Vaccine' 'Anti-Vaccine' 'Label']
     label
822  Label

In [ ]:
label

             label
0          Neutral
1          Neutral
2          Neutral
3      Pro-Vaccine
4     Anti-Vaccine
..             ...
855    Pro-Vaccine
856        Neutral
857   Anti-Vaccine
858    Pro-Vaccine
859   Anti-Vaccine

[860 rows x 1 columns]

In [ ]:
df2=pd.concat([label,exist],axis=1)

In [ ]:
df2

             label                   0   1
0          Neutral         0 : Neutral NaN
1          Neutral         1 : Neutral NaN
2          Neutral         2 : Neutral NaN
3      Pro-Vaccine     3 : Pro-Vaccine NaN
4     Anti-Vaccine    4 : Anti-Vaccine NaN
..             ...                 ...  ..
855    Pro-Vaccine   855 : Pro-Vaccine NaN
856        Neutral       856 : Neutral NaN
857   Anti-Vaccine  857 : Anti-Vaccine NaN
858    Pro-Vaccine   858 : Pro-Vaccine NaN
859   Anti-Vaccine  859 : Anti-Vaccine NaN

[860 rows x 3 columns]

In [ ]:
p_tests = []
for i in range(len(df2)):
    label = df2.iloc[i]['label'].strip().lower() 
    if label == 'anti-vaccine':
        p_tests.append(0)
    elif label == 'pro-vaccine':
        p_tests.append(1)
    elif label == 'neutral':
        p_tests.append(2)

In [ ]:
p_tests

[2,
 2,
 2,
 1,
 0,
 1,
 2,
 1,
 2,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 2,
 0,
 1,
 2,
 0,
 0,
 2,
 1,
 0,
 1,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 0,
 0,
 1,
 0,
 2,
 0,
 1,
 1,
 0,
 1,
 2,
 1,
 0,
 0,
 2,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 2,
 2,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 2,
 1,
 0,
 2,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 2,
 1,
 2,
 0,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 1,
 2,
 0,
 0,
 0,
 2,
 2,
 0,
 2,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 0,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 1,
 2,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 2,
 2,
 1,
 2,
 0,
 1,
 0,
 0,
 1,
 2,
 2,
 2,
 0,
 0,
 2,
 0,
 1,
 1,
 2,
 0,
 2,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 2,
 1,
 0,
 2,
 2,
 1,
 1,
 2,
 1,
 0,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 0,
 0,
 2,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 2,
 2,
 1,
 2,
 0,
 0,
 1,
 1,
 2,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 2,
 0,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 0,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 0,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 2,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 2,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 1,
 0,
 1,
 2,
 0,
 1,
 1,
 0,
 2,
 0,
 1,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 1,
 2,
 2,
 1,
 1,
 0,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 2,
 0,
 2,
 0,
 1,
 2,
 2,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 1,
 1,
 2,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 0,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 0,
 1,
 2,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 2,
 0,
 1,
 2,
 0,
 0,
 1,
 2,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 2,
 2,
 0,
 0,
 0,
 2,
 1,
 1,
 1,
 0,
 2,
 2,
 0,
 0,
 1,
 2,
 2,
 2,
 1,
 2,
 0,
 0,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 0,
 2,
 1,
 1,
 0,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 2,
 1,
 2,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 1,
 1,
 1,
 2,
 0,
 2,
 0,
 0,
 0,
 2,
 1,
 0,
 2,
 0,
 0,
 1,
 1,
 0,
 0,
 2,
 2,
 2,
 1,
 1,
 0,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 1,
 1,
 1,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 2,
 0,
 2,
 0,
 2,
 0,
 2,
 0,
 2,
 1,
 0,
 2,
 1,
 1,
 0,
 0,
 0,
 1,
 2,
 0,
 1,
 1,
 1,
 2,
 2,
 2,
 0,
 0,
 2,
 1,
 1,
 2,
 1,
 0,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 0,
 0,
 1,
 0,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 0,
 0,
 2,
 1,
 1,
 2,
 2,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 2,
 2,
 1,
 0,
 2,
 1,
 2,
 1,
 0,
 2,
 1,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 2,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 2,
 1,
 2,
 0,
 1,
 0]